set autoindent
set expandtab
set softtabstop=4
set shiftwidth=4
set shiftround

set number
syntax on
filetype plugin indent on
set cursorline
set cursorcolumn
set relativenumber

set textwidth=170
set colorcolumn=+1

set incsearch
set hlsearch

"morhetz/gruvbox
"autocmd vimenter * ++nested colorscheme gruvbox
set background=dark

"Map keys
map <F2> : vsp
map <F3> : NERDTreeToggle
map <F4> : NERDTreeFocus
map <F5> : spli
map <F6> : tabnew
map <F7> : tabn
":new file !mkdir folder
" ctrl+w + {[h,j,k,l] our [up, left, rigt, down]} => move in the windows
" tabm, tabm 0 => move to last tab our first tab
" tabfirst, tablast => go to first tab our last tab
" tabn, tabp => go to next tab our previw tab
" in tree, t open new tab, T open new tab silence
" in tree, i open new window in split
" in tree, shift + i, show hidden files and folder

map <F12> : PlugInstall
"Auto instalaci`on de plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent execute '!curl -fLo '.'~/.vim/autoload/plug.vim --create-dirs 
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
"===============================================================================

"Airline
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

"SuRound
Plug 'tpope/vim-surround'

"terminus
Plug 'wincent/terminus'

"AutoComplte
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'neoclide/coc.nvim', { 'do': { -> 'yarn install' } }
Plug 'davidhalter/jedi-vim'

"Rust plugin
Plug 'rust-lang/rust.vim'

"Go Plugin
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

"Nerd Tree
Plug 'preservim/nerdtree'

"cerrador de simbolos
Plug 'dhruvasagar/vim-pairify'

"Rust plugin
Plug 'rust-lang/rust.vim'

Plug 'jiangmiao/auto-pairs'

Plug 'morhetz/gruvbox'

"===============================================================================
call plug#end()
