#!/bin/sh

# ##############################################################################
# #                                  ENV VARS                                  # 
# ##############################################################################

export BROWSER=firefox
export EDITOR=vim
export _JAVA_AWT_WM_NONREPARENTING=1 # Fix for JetBrains IDEs

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }
start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

# Autostart Apps
killall clipcatd
killall power_pc_2am.sh
killall listeng_port_listeng.sh

$HOME/.config/polybar/launch.sh
$HOME/Source/scripts/bash/power_pc_2am.sh &
$HOME/Source/scripts/bash/listeng_port_listeng.sh &
picom --experimental-backends &
conky &
clipcatd &


# Set wallpaper
feh --bg-fill "$HOME/Source/Wallpapers/obey.png"
# Hex Gang
hsetroot -solid "#192022"

# I hate mouse drift.
xset m 0 0

# Fix for eww bar not hiding on a fullscreen window.

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

bspc monitor -d 1 2 3 4 5 6

rule kitty                          desktop=1
rule firefox                        desktop=2
rule pcmanfm                        desktop=5
rule mpv                            desktop=6

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

config pointer_modifier             Mod4
#rule Code                           desktop=4

config window_gap                   10
config left_padding                 10

config split_ratio                  0.5
config borderless_monocle           true
config gapless_monocle              true

# ##############################################################################
# #                                 MISCELLANEOUS                              #
# ##############################################################################
