#!/bin/sh

# ##############################################################################
# #                                  ENV VARS                                  # 
# ##############################################################################

export BROWSER=firefox
export EDITOR=vim
export _JAVA_AWT_WM_NONREPARENTING=1 # Fix for JetBrains IDEs

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }
start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################
#loadkeymap
setxkbmap -layout es

# Autostart Apps
clipcatctl clear
killall clipcatd
#killall screenkey
killall power_pc_2am.sh
killall listeng_port_listeng_diff.sh

dead-notification-center &
$HOME/.config/polybar/launch.sh
$HOME/Source/scripts/bash/power_pc_2am.sh &
$HOME/Source/scripts/bash/listeng_port_listeng_diff.sh &
picom --experimental-backends &
conky &
clipcatd &
#screenkey -s small &

# Set wallpaper
feh --bg-fill "$HOME/Source/Wallpapers/3006390.jpg"


nm-applet &
blueman-applet &

# Hex Gang
hsetroot -solid "#192022"

# I hate mouse drift.
xset m 0 0

#fix cursor
xsetroot -cursor_name left_ptr &
# Fix for eww bar not hiding on a fullscreen window.

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

bspc monitor -d 1 2 3 4 5 6 7

rule kitty                          desktop=1
rule firefox                        desktop=2
rule pcmanfm                        desktop=5
rule mpv                            desktop=6

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

config pointer_modifier             Mod4
#rule Code                           desktop=4

config window_gap                   10
config left_padding                 10

config split_ratio                  0.5
config borderless_monocle           true
config gapless_monocle              true


/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
disown
# ##############################################################################
# #                                 MISCELLANEOUS                              #
# ##############################################################################
